server:
  port: 40910 # 线上运行端口

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 阿里云服务器的数据库连接 (宝塔本地就是 127.0.0.1)
    url: jdbc:mysql://127.0.0.1:3306/personal-system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    # ⚠️ 【极其重要】：请务必将下方替换为你在宝塔面板中设置的真实 MySQL 密码！
    password: YueLin020714@