spring:
  profiles:
    # 默认激活本地测试环境，在 IDEA 启动时会自动读取 application-test.yml
    active: prod

  # 邮件服务配置 (前后端通用)
  mail:
    host: smtp.qq.com
    port: 465
    username: 1585037731@qq.com # 你的发件邮箱
    password: frewpwwolyprihec    # 你的邮箱授权码（不是登录密码）
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true

mybatis-plus:
  # MyBatis-Plus 的 xml 映射文件路径
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    # 打印 SQL 语句到控制台，方便调试
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名自动映射 (如 user_id 映射到 userId)
    map-underscore-to-camel-case: true